import type { Article, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

const articles: Article[] = [
  {
    id: 'tech-1',
    headline: 'Next-Gen Quantum Computer Unveiled, Promises Unprecedented Speeds',
    content: 'Scientists at QuantumLeap Inc. have revealed their latest quantum computing processor, the "Chrono-Q", which they claim can perform calculations thousands of times faster than current supercomputers. The breakthrough relies on a new method for stabilizing qubits, the fundamental units of quantum information. This could revolutionize fields from medicine to materials science.',
    source: 'Tech Today',
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    category: 'Technology',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  },
  {
    id: 'ai-1',
    headline: 'New AI Model Can Write and Debug Code Like a Human Developer',
    content: 'A startup named "Cognition Labs" has developed an AI named "Devin" that can understand complex software engineering tasks and write, debug, and deploy code autonomously. During a live demo, Devin successfully completed a small project from a single-sentence prompt, showcasing its advanced reasoning and planning capabilities.',
    source: 'AI Insider',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    category: 'AI',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
  },
  {
    id: 'sports-1',
    headline: 'Dynamos FC Clinch Championship in a Thrilling Final Minute Goal',
    content: 'In a nail-biting conclusion to the season, Dynamos FC secured the league title with a spectacular goal in the final minute of stoppage time against their rivals, the Titans. The stadium erupted as striker Leo Vance headed the ball into the net, ending a decade-long championship drought for the team.',
    source: 'Sports Weekly',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    category: 'Sports',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
  },
  {
    id: 'business-1',
    headline: 'Global Markets React to Surprise Interest Rate Hike',
    content: 'The Federal Reserve announced an unexpected 0.25% hike in interest rates, sending shockwaves through global financial markets. The move, aimed at curbing inflation, led to a volatile trading session, with tech stocks seeing the largest drop. Economists are divided on the long-term impact of the decision.',
    source: 'Financial Times',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    category: 'Business',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
  },
  {
    id: 'gaming-1',
    headline: 'Highly Anticipated RPG "Elden Ring 2" Leaked Trailer Excites Fans',
    content: 'A short, blurry trailer for what appears to be a sequel to the critically acclaimed RPG "Elden Ring" was leaked online, sending the gaming community into a frenzy. The trailer showcases new environments and a mysterious new character, though the developer has yet to make an official announcement.',
    source: 'GameSpot',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Gaming',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
  },
  {
    id: 'education-1',
    headline: 'Universities Adopt AI Tutors to Personalize Student Learning',
    content: 'A growing number of universities are integrating AI-powered tutoring systems into their curriculum. These systems provide personalized feedback, answer student questions 24/7, and adapt to individual learning paces, promising a more effective and accessible educational experience.',
    source: 'Education Forward',
    publishedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Education',
    imageUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
  },
  {
    id: 'health-1',
    headline: 'Breakthrough in Alzheimer\'s Research: New Drug Slows Cognitive Decline',
    content: 'A clinical trial for a new drug, "CogniClear," has shown significant success in slowing the progression of cognitive decline in early-stage Alzheimer\'s patients. Researchers are optimistic that this could be a turning point in the fight against the neurodegenerative disease.',
    source: 'Medical News',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Health',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
  },
  {
    id: 'tech-2',
    headline: 'The Rise of Foldable Phones: Are They the Future?',
    content: 'Foldable smartphones are becoming increasingly popular, with major manufacturers releasing new and improved models. While still a premium product, prices are beginning to fall. Tech analysts weigh in on whether the flexible form factor is a gimmick or the true evolution of mobile devices.',
    source: 'Gadget Guru',
    publishedAt: new Date(Date.now() - 2.2 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Technology',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
  },
   {
    id: 'ai-2',
    headline: 'Ethical AI: The Frameworks We Need for a Responsible Future',
    content: 'As artificial intelligence becomes more integrated into society, the call for strong ethical frameworks is growing louder. Experts from academia, industry, and government are collaborating to create guidelines that ensure fairness, transparency, and accountability in AI systems.',
    source: 'Ethics in Tech',
    publishedAt: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'AI',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
  },
  {
    id: 'sports-2',
    headline: 'eSports Viewership Surpasses Traditional Sports in Key Demographics',
    content: 'A new report indicates that for viewers aged 18-34, major eSports tournaments are now drawing larger audiences than many traditional sporting events, including baseball and hockey finals. This shift highlights a significant change in media consumption habits and the growing legitimacy of competitive gaming.',
    source: 'The Score',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Sports',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
  },
];

export function getNewsArticles(): Article[] {
  // In a real app, this would be an API call.
  // We sort by date to simulate a real feed.
  return articles.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
}
